---
title: "About"
author: "IS415 T14"
date: "10/19/2020 (updated: `r Sys.Date()`)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# IS415 Project: East Kalimantan as the new J-Town
By Team 14: [Ng Xun Jie](https://www.linkedin.com/in/xunjieng53b81m), [Erika Aldisa Gunawan](https://www.linkedin.com/in/erikaaldisa/), [Sean Lee Jun Hui](https://www.linkedin.com/in/ljhsean)

This project is done for IS415 Geospatial Analytics & Application (SMUX-X), a module in Singapore Management University (SMU) with the guidance of Professor Kam Tin Seong.

This project is a geospatial analytics project which looks at **Spatially Constrained Clustering** analysis method to conduct profiling and clustering of the proposed area of Indonesia's new capital city in East Kalimantan, near the cities of Balikpapan and Samarinda.

The links you want to check out:

1. [Project Web page]()

The web page contains everything about our project including our **poster**, **video** and **research paper.**

2. [Project R Shiny application]()

The R Shiny application allows user to engage with the dataset variables which will change the map visualization and analysis value.